version: '3.4'

services:
  ably-test-mysql:
    image: mysql:5.7
    container_name: ably-test-backend-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ably-test
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --lower_case_table_names=1

  ably-test-backend:
    image: ably-test-backend
    build:
      context: .
      dockerfile: infra/local/docker/Dockerfile
    container_name: ably-test-backend-backend
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/htdocs/www
    depends_on:
      - ably-test-mysql
    links:
      - ably-test-mysql
    command:
      - bash
      - -c
      - |
        ./infra/wait_for_it.sh ably-test-mysql:3306
        make run-ably-test-backend

  ably-test-nginx:
    image: nginx:stable
    container_name: ably-test-nginx
    restart: always
    hostname: 'w.ably-test.local'
    volumes:
      - ./infra/local/nginx/ably-test.conf:/etc/nginx/conf.d/ably-test.conf:ro
      - ./infra/local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/local/cert:/etc/nginx/cert/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ably-test-backend
    links:
      - ably-test-backend
