# Generated by Django 4.1.1 on 2022-09-11 12:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("nickname", models.CharField(max_length=64, verbose_name="닉네임")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                ("name", models.CharField(max_length=32, verbose_name="사용자 이름")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="KR", verbose_name="핸드폰 번호"
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 리스트",
                "db_table": "user",
            },
        ),
    ]
