# Generated by Django 4.1.1 on 2022-09-11 14:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="KR", unique=True, verbose_name="핸드폰 번호"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "phone")},
        ),
    ]
