# Generated by Django 4.1.1 on 2022-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_email_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=64, unique=True, verbose_name="닉네임"),
        ),
    ]
