PHONE_VALIDATION_CODE_EXPIRE_MIN = 5

USAGE_TYPE_SIGN_UP = "SIGN_UP"
USAGE_TYPE_CHANGE_PASSWORD = "CHANGE_PASSWORD"
PHONE_VALIDATION_USAGE_TYPE_CHOICES = [
    (USAGE_TYPE_SIGN_UP, "회원가입 전화번호 인증"),
    (USAGE_TYPE_CHANGE_PASSWORD, "비밀번호 변경 전화번호 인증"),
]

RSA_PRIVATE_KEY_BITS = 4096

JWT_ALGORITHM_RSA = "RS256"

SIGN_UP_PHONE_VALIDATION = "SIGN_UP_PHONE_VALIDATION"
USERS_ME_AUTHORIZATION = "USERS_ME_AUTHORIZATION"
TOKEN_VALIDATION_KEY_TYPE_CHOICES = [
    (SIGN_UP_PHONE_VALIDATION, "회원가입 전화 인증"),
    (USERS_ME_AUTHORIZATION, "사용자 로그인 인증"),
]
