# Generated by Django 4.1.1 on 2022-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonevalidationcode",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("SIGN_UP", "회원가입 전화번호 인증"),
                    ("PASSWORD_RESET", "비밀번호 재설정 전화번호 인증"),
                ],
                max_length=16,
                verbose_name="사용 용도 유형",
            ),
        ),
    ]
