# Generated by Django 4.1.1 on 2022-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0002_alter_phonevalidationcode_usage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyvalidation",
            name="key_type",
            field=models.CharField(
                choices=[
                    ("SIGN_UP_PHONE_VALIDATION", "회원가입 전화 인증"),
                    ("USERS_ME_AUTHORIZATION", "사용자 로그인 인증"),
                    ("PASSWORD_RESET_PHONE_VALIDATION", "비밀번호 재설정"),
                ],
                max_length=64,
                verbose_name="키 유형",
            ),
        ),
    ]
